// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9eOwlzj2iSJ44fXWSROcFCdYIiCRHfA4',
    appId: '1:99839453275:web:58f712acc894217f55f77e',
    messagingSenderId: '99839453275',
    projectId: 'firabaseapp-51045',
    authDomain: 'firabaseapp-51045.firebaseapp.com',
    storageBucket: 'firabaseapp-51045.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMaQRWilsNTdO09i_1bVViWhMAasb0WIU',
    appId: '1:99839453275:android:51fa8f1848b513ef55f77e',
    messagingSenderId: '99839453275',
    projectId: 'firabaseapp-51045',
    storageBucket: 'firabaseapp-51045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVRYDFMi-D1D-QYnWGraqn-UwqrPfu0Ss',
    appId: '1:99839453275:ios:c8e8ee63c26c53d355f77e',
    messagingSenderId: '99839453275',
    projectId: 'firabaseapp-51045',
    storageBucket: 'firabaseapp-51045.appspot.com',
    iosClientId: '99839453275-argv6hmn5409kcluuj6lajali3jeif4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVRYDFMi-D1D-QYnWGraqn-UwqrPfu0Ss',
    appId: '1:99839453275:ios:a8a9e8b7357960fa55f77e',
    messagingSenderId: '99839453275',
    projectId: 'firabaseapp-51045',
    storageBucket: 'firabaseapp-51045.appspot.com',
    iosClientId: '99839453275-11m1ce0e397fgr99ik0htl4123a81j65.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase3.RunnerTests',
  );
}
