// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBL2Yvf7cGAXzrjl6IdHq4Hl0jBqp629Q',
    appId: '1:1083176832169:web:93c1f63e32124227e12db8',
    messagingSenderId: '1083176832169',
    projectId: 'test-b5031',
    authDomain: 'test-b5031.firebaseapp.com',
    storageBucket: 'test-b5031.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9pYS3Uv7IVwy-PHIwJa24jzsCyV2zdYs',
    appId: '1:1083176832169:android:07b60451bb87ae4de12db8',
    messagingSenderId: '1083176832169',
    projectId: 'test-b5031',
    storageBucket: 'test-b5031.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeowAcy06NZGS5CMSvaoeu9tM6PZkMPWw',
    appId: '1:1083176832169:ios:44a8e0325384d1c1e12db8',
    messagingSenderId: '1083176832169',
    projectId: 'test-b5031',
    storageBucket: 'test-b5031.appspot.com',
    iosBundleId: 'com.example.testFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeowAcy06NZGS5CMSvaoeu9tM6PZkMPWw',
    appId: '1:1083176832169:ios:f084ed4587d690f9e12db8',
    messagingSenderId: '1083176832169',
    projectId: 'test-b5031',
    storageBucket: 'test-b5031.appspot.com',
    iosBundleId: 'com.example.testFirebase1.RunnerTests',
  );
}
